[package]
name = "testeFicha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.9.0-alpha.0", features = [] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
